package com.htp.controller;


import com.htp.controller.requests.OrderCreateRequest;
import com.htp.domain.Order;
import com.htp.repository.OrderDao;
import com.htp.tools.Util;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

import java.sql.Timestamp;
import java.util.Date;
import java.util.List;

@RestController
@CrossOrigin
@RequestMapping(value = "/rest/order")
public class ProworkController {
    @Autowired
    @Qualifier("orderDaoImpl")
    private OrderDao orderDao;

    @GetMapping
    @ResponseStatus(HttpStatus.OK)
    public ResponseEntity<List<Order>> getOrders() {
        return new ResponseEntity<>(orderDao.findAll(), HttpStatus.OK);
    }

    @PostMapping
    @Transactional
    @ResponseStatus(HttpStatus.CREATED)
    public ResponseEntity<Order> createOrder(@RequestBody OrderCreateRequest request) {
        Order order = new Order();
        //userID is empty - will be generated by DB
        order.setType(request.getType());
        order.setDescription(request.getDescription());
        order.setAddress(request.getAddress());
        order.setLatitude(request.getLatitude());
        order.setLongtitude(request.getLongtitude());
        order.setIdClient(request.getIdClient());
        order.setCountWorker(request.getCountWorker());
        order.setDateCreate(new Timestamp(new Date().getTime()));
        order.setDateFromOrder(Util.convertStringToTimestamp(request.getDateFromOrder()));
        order.setStatus(request.getStatus());
        order.setPrioritet(request.getPrioritet());

        Order savedOrder = orderDao.save(order);

        return new ResponseEntity<>(savedOrder, HttpStatus.OK);
    }

    @DeleteMapping("/{id}")
    @ResponseStatus(HttpStatus.OK)
    public ResponseEntity<Long> deleteUser(@PathVariable("id") Long orderId) {
        orderDao.delete(orderId);
        return new ResponseEntity<>(orderId, HttpStatus.OK);
    }

}
